### ISSUE TITLE
Crash decoding pcap file

### ISSUE THREAD

**Issue by colinnewell** [colinnewell/pcap2mysql-log#25]
Got this crash with a capture:

```
panic: runtime error: makeslice: len out of range

goroutine 35 [running]:
github.com/colinnewell/pcap2mysql-log/pkg/mysql/decoding.readLenEncBytes(0x62ab40, 0xc00058e150, 0x6306a0, 0xcc0eb0, 0x593020, 0xc00058011a, 0x0)
	/home/cnewell/git/pcap2mysql-log/pkg/mysql/decoding/packet.go:40 +0x75
github.com/colinnewell/pcap2mysql-log/pkg/mysql/decoding.(*RequestDecoder).decodeExecute(0xc0004c0040, 0xc000594194, 0x49, 0x353, 0xc0004cf9b8, 0x4746f4, 0xc0004ba150)
	/home/cnewell/git/pcap2mysql-log/pkg/mysql/decoding/request.go:239 +0x565
github.com/colinnewell/pcap2mysql-log/pkg/mysql/decoding.(*RequestDecoder).Write(0xc0004c0040, 0xc000594194, 0x49, 0x353, 0xc0004c3000, 0x4c9419, 0xc000594194)
	/home/cnewell/git/pcap2mysql-log/pkg/mysql/decoding/request.go:135 +0x305
github.com/colinnewell/pcap2mysql-log/pkg/mysql/packet.(*MySQLPacketWriter).Write(0xc0004cfa80, 0xc000594194, 0x49, 0x353, 0x49, 0x0, 0x0)
	/home/cnewell/git/pcap2mysql-log/pkg/mysql/packet/split.go:39 +0xe2
github.com/colinnewell/pcap2mysql-log/pkg/mysql/packet.Copy(0x62ad20, 0xc0004ba140, 0x62acc0, 0xc0004c0040, 0x64, 0x7f0d357d1108, 0x0)
	/home/cnewell/git/pcap2mysql-log/pkg/mysql/packet/copy.go:24 +0x1dc
github.com/colinnewell/pcap2mysql-log/pkg/mysql/decoding.(*MySQLConversationReaders).ReadRequestDecoder(0xc00000e2c0, 0x62ad20, 0xc0004ba140, 0xc0004b8270, 0x1, 0x4, 0x4, 0x20016ad, 0x0, 0x40016ad, ...)
	/home/cnewell/git/pcap2mysql-log/pkg/mysql/decoding/reader.go:163 +0x1da
github.com/colinnewell/pcap2mysql-log/pkg/mysql/decoding.(*MySQLConversationReaders).ReadStream(0xc00000e2c0, 0x62c0a0, 0xc0004b8240, 0x1, 0x4, 0x4, 0x20016ad, 0x0, 0x40016ad, 0x0, ...)
	/home/cnewell/git/pcap2mysql-log/pkg/mysql/decoding/reader.go:103 +0x468
github.com/colinnewell/pcap2mysql-log/pkg/tcp.(*StreamFactory).New.func1(0xc00000e2e0, 0xc0004b8240, 0x1, 0x4, 0x4, 0x20016ad, 0x0, 0x40016ad, 0x0, 0x4, ...)
	/home/cnewell/git/pcap2mysql-log/pkg/tcp/factory.go:25 +0xc9
created by github.com/colinnewell/pcap2mysql-log/pkg/tcp.(*StreamFactory).New
	/home/cnewell/git/pcap2mysql-log/pkg/tcp/factory.go:24 +0x22e
```

**Comment by colinnewell** [comment]
Fixed in e8b9cab730748e9902fa69edc011dd234ce83886.
